base_url = "https://ghost.florist"
title = "ghost.florist"
description = "I makes things, mostly on computers."
compile_sass = false
build_search_index = false

[extra.quote]
body = "We build our legacy piece by piece and maybe the whole world will remember you or maybe just a couple of people, but you do what you can to make sure you're still around after you're gone."
from = "A Ghost Story"

[[extra.projects]]
title = "Hush"
description = "A quiet place for two; experimental messaging without identity."
url = "https://github.com/ghstf/hush"

[[extra.links]]
name = "github"
url = "https://github.com/ghstf"

[[extra.links]]
name = "literal.club"
url = "https://literal.club/ghstf"

[[extra.links]]
name = "record.club"
url = "https://record.club/ghstf"

[[extra.links]]
name = "mastodon"
url = "https://mastodon.social/@ghstf"

[[extra.links]]
name = "email"
url = "mailto:dear@ghost.florist"
